CREATE TABLE USERS (
  ID SERIAL PRIMARY KEY,
  NAMES VARCHAR(20) NOT NULL,
  AGE INTEGER NOT NULL,
  BIRTH DATE NOT NULL
);

INSERT INTO USERS (NAMES, AGE, BIRTH)
VALUES  ('Nicola Martinez', 27, '1994-07-01' );